name: Deploy to EC2

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible
          
      - name: Install AWS Python Libraries
        run: |
          python -m pip install --upgrade pip
          pip install botocore boto3

      - name: Run Ansible playbook
        run: ansible-playbook .github/workflows/deployment/deploy.yml -i .github/workflows/deployment/inventory.ini -vvv
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }} 
