name: Deploy to EC2

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible
          
      - name: Check AWS Secrets
        run: |
          echo "AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}"
          echo "AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}"
          echo "AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}"

      - name: Run Ansible playbook
        run: |
          # ansible-playbook .github/workflows/deployment/deploy.yml
          ansible-playbook .github/workflows/deployment/deploy.yml -i .github/workflows/deployment/inventory.ini
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }} 
